site_name: Swarovski Optik OpenAPI Documentation
site_url: https://swarovskioptik.github.io/openapi-docu/
theme:
  name: readthedocs
nav:
  - Home: 'index.md'
  - Explanations:
    - 'exp/ax-visio.md'
    - 'exp/so-comm-sdk.md'
    - 'exp/openapi.md'
  - Tutorials:
    - 'tut/requesting-an-api-key.md'
    - 'tut/using-the-example-application.md'
  - How-To Guides:
    - 'how/adding-the-so-comm-sdk-libraries.md'
    - 'how/using-the-so-comm-outside-api.md'
    - 'how/using-kotlin-extensions.md'
  - References:
    - 'ref/releases.md'
    - 'ref/api-reference.md'
    - 'ref/example-applications.md'
    - 'ref/glossary.md'
    - 'ref/exif_field_descriptions.md'
  - Support:
    - 'support.md'
    - 'impressum.md'
